djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from pols import views as pols_views
from home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pols/', pols_views.question_list),
    path('pols/<int:question_id>/', pols_views.question_detail),
    path('', home_views.home)
]

home/models.py
from django.db import models

# Create your models here.

pols/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    is_open_question = models.BooleanField(default=True)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=2137)

home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

pols/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question


def question_list(request):
    questions = Question.objects.all()
    return render(request, 'pols/question_list.html', {'questions': questions})


def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'pols/question_detail.html', {'question': question})

templates/home.html
<h1>Strona</h1>
<p>Witaj, <b>{% if not request.user.is_authenticated %}niezalogowany{% else %}{{ request.user }}{% endif %}</b></p>
<ul>
<li><a href="pols">Ankiety</a></li>
</ul>

templates/pols/question_detail.html
<link rel="styleshet" href="/style.css">

<h1>{{ question.question_text }}</h1>
<h2>Odpowiedzi</h2>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} ({{ choice.votes }} głosy)</li>
{% endfor %}
</ul>
{% if question.answer_set.all %}
    <h2>Odpowiedzi tekstowe</h2>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.answer }}</li>
    {% endfor %}
    </ul>
{% endif %}

templates/pols/question_list.html
<!DOCTYPE html>
<html>

<body>
<table class="tabela">
    <tr>
        <th>Id</th>
        <th>Tytuł</th>
        <th>Data</th>
        <th>Otwarte</th>
    </tr>
    {% for question in questions %}
        <tr>
        <td>
            <a href="{{ question.id }}">{{ question.pk }}</a>
        </td>
        <td>
            {{ question.question_text }}
        </td>
        <td>
            {{ question.pub_date }}
        </td>
        <td>
            {% if question.is_open_question %}
                Tak
            {% else %}
                Nie
            {% endif %}
        </td>
        </tr>

   {% endfor %}
</table>
</body>
</html>